import { UnionToArray, unionToArray } from "@/types/union";

export type WeaponType =
  | "Dagger"
  | "Straight Sword"
  | "Curved Sword"
  | "Greatsword"
  | "Colossal Sword"
  | "Thrusting Sword"
  | "Heavy Thrusting Sword"
  | "Curved Greatsword"
  | "Katana"
  | "Twinblade"
  | "Hammer"
  | "Great Hammer"
  | "Flail"
  | "Axe"
  | "Greataxe"
  | "Spear"
  | "Great Spear"
  | "Halberd"
  | "Reaper"
  | "Whip"
  | "Fist"
  | "Claw"
  | "Colossal Weapon"
  | "Torch"
  | "Small Shield"
  | "Medium Shield"
  | "Greatshield"
  | "Staff"
  | "Light Bow"
  | "Bow"
  | "Greatbow"
  | "Crossbow"
  | "Ballista";

export type WeaponAffinityRaw =
  | "-"
  | "Standard"
  | "Heavy"
  | "Keen"
  | "Quality"
  | "Magic"
  | "Frost"
  | "Fire"
  | "Flame Art"
  | "Lightning"
  | "Sacred"
  | "Poison"
  | "Blood"
  | "Occult";

export type WeaponAffinity = Exclude<WeaponAffinityRaw, "-">;

export type CanApplyAshOfWarRaw = "Yes" | "No";

export type WeaponTypeColumnRaw =
  | "AA"
  | "AB"
  | "AC"
  | "AD"
  | "AE"
  | "AF"
  | "AJ"
  | "AH"
  | "AI"
  | "AK"
  | "AS"
  | "AT"
  | "AU"
  | "AQ"
  | "AR"
  | "AL"
  | "AM"
  | "AN"
  | "AO"
  | "AP"
  | "O"
  | "P"
  | "Q"
  | "R"
  | "S"
  | "T"
  | "U"
  | "V"
  | "W"
  | "X"
  | "Y"
  | "Z";

// https://docs.google.com/spreadsheets/d/1BTwjJaSX8iEK7TjUi0TbCY34apgH_028_a_j2XcITqY/edit?gid=0#gid=0
export type WeaponAffinityColumnRaw =
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | ""
  | "";
